# ------------- Site settings -------------
lastupdate: 21/10/2015
title: Papyrus Resources
me: Jean-Michel Bruel
email: bruel@irit.fr
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://jmbruel.github.io" # the base hostname & protocol for your site
repository: https://github.com/jmbruel/design
description: Papyrus teaching materials
google_analytics: false
facebook_share: true
twitter_share: true
disqus_shortname: jmbruel
# ------------- Variables -------------
github_username: jmbruel
twitter_username: jmbruel
linkedin_username: jmbruel
googleplus_username: JeanMichelBruel
facebook_username: jmbruel
papyrus: <a href="https://www.eclipse.org/papyrus/">Papyrus</a>
uncheckedStatus: question-circle
# ------------- Build settings -------------

markdown: kramdown

gems:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font

#exclude: [vendor,*.sh]
