# Site settings
lastupdate: 18/10/2015
title: JMB's Website
email: bruel@irit.fr
github_username: jmbruel
twitter_username: jmbruel
linkedin_username: jmbruel
description: > # this means to ignore newlines until "baseurl:"
  Baked with Jekkyl, Asciidoctor.
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://jmbruel.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font

exclude: [vendor]
