# Site settings
lastupdate: 18/10/2015
title: Papyrus Resources
email: bruel@irit.fr
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://jmbruel.github.io" # the base hostname & protocol for your site
repository: https://github.com/jmbruel/design
github_username: jmbruel
twitter_username: jmbruel
linkedin_username: jmbruel
googleplus_username: JeanMichelBruel
facebook_username: jmbruel
description: Papyrus teaching materials
# Build settings
markdown: kramdown

gems:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font

exclude: [vendor]
