# Site settings
title: Your awesome title
email: your-email@domain.com
github_username: jmbruel
twitter_username: jmbruel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/design" # the subpath of your site, e.g. /blog/
url: "http://jmbruel.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style
    - icons=font

exclude: [vendor]
